### PR TITLE
fix: unique key name was not set correctly.

### PR DESCRIPTION
**Pull request by beneiltis**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?
When you use multiple @CosmosUniqueKey() decorators, cosmos db will complain about using the same constraint key.

Issue Number: N/A

## What is the new behavior?
You can now user @CosmosUniqueKey() for multiple properties like intended from Microsoft.
I guess it was just a typo :-)

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by manekinekko** [comment]
Hey @beneiltis is this PR still valid?

**Comment by beneiltis** [comment]
Yes it is. But I mixed stuff into the branch so I decided to recreate it tomorrow. But you just need to switch the variable 😜 I guess it was a simple typo. 

Cheers Bene 

Von meinem iPhone gesendet

**Comment by manekinekko** [comment]
I'll wait for your PR tomorrow. No hurries 😃

Cheers.

**Comment by beneiltis** [comment]
New PR is waiting for you :-)

**Pull request closed without merging**
